### ISSUE TITLE
Update cock command

### ISSUE THREAD

**Issue by cannedyeti** [vevinkirk/eeekgamesbot#33]
Have the bot generate a random int from 2-12 (or something) and return it to the user who requests it.

Example:

user uses `/cock`

bot returns "Your cock is 2 inches!"

Maybe randomize units of measurements? Inches, cm, etc. Maybe attach a string to each number? Insult if its a small number, congrats if its large?

**Comment by vevinkirk** [comment]
https://github.com/vevinkirk/eeekgamesbot/pull/42
